### ISSUE TITLE
having some errors while running this project

### ISSUE THREAD

**Issue by Himank17Gupta** [matheuscr30/Handwritten-Equation-Recognition---CNN#4]
hello devs, I cloned this project and ran in my machine, but after the predict click, it alerts out "some error occured"
while on cli it logs "FileNotFoundError: [Errno 2] No such file or directory: 'aux.png'"
can you please help me out in running this project.

![errorStack](https://user-images.githubusercontent.com/54303210/92469924-45e1e300-f1f3-11ea-9cc1-e449f25baaee.PNG)

**Comment by matheuscr30** [comment]
I gave a quick look here and I think the dependencies are not updated. 
I'll fix that in the next hour

**Comment by matheuscr30** [comment]
Ok, it was done

**Comment by Himank17Gupta** [comment]
Hello @matheuscr30 , i'm still not sure if the error is resolved, also in the requirement.txt there is no Pillow module, which is throwing error 
"from PIL import Image
ModuleNotFoundError: No module named 'PIL'"
after I did install pillow using pip, it still gives me final runtime error on predict which says 

  File "F:\handwritten3\Handwritten-Equation-Recognition---CNN\venv\lib\site-packages\PIL\Image.py", line 2131, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'aux.png'

**Comment by matheuscr30** [comment]
I updated the reqs with Pillow, I cloned the repository from zero, tested again and everything works
Are you using Python3 ?

**Comment by matheuscr30** [comment]
Or maybe it's a problem with Windows, because I'm testing in arch linux

**Comment by Himank17Gupta** [comment]
I work with windows...have python 3.8 installed in my machine, uses python as command, is there any possible workaround?

**Comment by matheuscr30** [comment]
I'll test today on Windows and solve the problem

**Comment by sshivam010** [comment]
Hi, I am having the same issue. Can you help me ?

**Comment by sshivam010** [comment]
I am running it on windows with python 3.8 installed
